Cargo.toml
pallas-alonzo/Cargo.toml
pallas-alonzo/src/crypto.rs
pallas-alonzo/src/lib.rs
pallas-chainsync/Cargo.toml
pallas-chainsync/examples/blocks.rs
pallas-chainsync/examples/headers.rs
pallas-crypto/Cargo.toml
pallas-crypto/README.md
pallas-crypto/src/hash/hash.rs
pallas-crypto/src/hash/hasher.rs
pallas-crypto/src/hash/mod.rs
pallas-crypto/src/lib.rs
pallas/Cargo.toml
pallas/src/lib.rs

I also bumped to the latest version of cryptoxide. There's been a lot of performance improvements that have been made since then and this would be a shame to not leverage this (though it's mostly for `Curve25519`).
This PR remove the temporary (useless?) serialisation of the `Encode`-able object.  That way we now have a memory overhead allocation to do the hash.

Offer a faster way to compute the hash of an encodable object

---

pallas-alonzo/src/model.rs
pallas-crypto/src/hash/hash.rs

Followup on #23 we can start using the proper hash types instead of the heap allocated byte array.

make sure of the `pallas_crypto::Hash` type

---

pallas-miniprotocols/examples/chainsync-blocks.rs
pallas-miniprotocols/examples/chainsync-headers.rs
pallas-miniprotocols/src/chainsync/clients.rs
pallas-miniprotocols/src/chainsync/codec.rs
pallas-miniprotocols/src/chainsync/protocol.rs
pallas-miniprotocols/src/payloads.rs

Instead of forcing the consumer agent to extract a cursor from the payload, we just pass the bytes to the observer. In this way, implementors can decide when / how to execute the decoding.
Bonus: we now pass the tip of the chain to the observer (needed for Oura).

chore: Simplify ChainSync agent logic

---

pallas-miniprotocols/src/chainsync/buffer.rs
pallas-miniprotocols/src/chainsync/mod.rs
pallas-miniprotocols/src/chainsync/protocol.rs
pallas-miniprotocols/src/common.rs

This PR introduces a memory buffer to handle chain rollbacks.
This structure is intended to facilitate the process of managing rollbacks in a chain sync process. The goal is to keep `points` in memory until they reach a certain depth (# of confirmations). If a rollback happens, the buffer will try to find the intersection, clear the orphaned points and keep the remaining still in memory. Further forward rolls will accumulate from the intersection.
It works by keeping a `VecDeque` data structure of points, where roll-forward operations accumulate at the end of the deque and retrieving confirmed points means to pop from the front of the deque.
Notice that it works by keeping track of points, not blocks. It is meant to be used as a lightweight index where blocks can then be retrieved from a …

feat: Implement rollback buffer

---

examples/block-download/src/main.rs
pallas-miniprotocols/examples/blockfetch.rs
pallas-miniprotocols/examples/chainsync-blocks.rs
pallas-miniprotocols/examples/chainsync-headers.rs
pallas-miniprotocols/examples/handshake-client.rs
pallas-miniprotocols/examples/handshake-node.rs
pallas-miniprotocols/examples/localstate-chainpoint.rs
pallas-miniprotocols/examples/txsubmission-naive.rs
pallas-miniprotocols/src/blockfetch/mod.rs
pallas-miniprotocols/src/chainsync/agents.rs
pallas-miniprotocols/src/chainsync/mod.rs
pallas-miniprotocols/src/handshake/agents.rs
pallas-miniprotocols/src/handshake/mod.rs
pallas-miniprotocols/src/handshake/n2c.rs
pallas-miniprotocols/src/handshake/n2n.rs
pallas-miniprotocols/src/handshake/protocol.rs
pallas-miniprotocols/src/localstate/mod.rs
pallas-miniprotocols/src/machines.rs
pallas-miniprotocols/src/txsubmission/mod.rs
pallas-multiplexer/src/bearers.rs

Very heavy refactoring of the whole state-machine implementation framework. The goal is to decouple the state-machine execution from any side-event by turning inbound / outbound message processing into pure functions.
This makes the implementation easier to follow, but more important, it allows us to create easy tests of the formal business logic of each state-machine without any networking concerns.

refactor(miniprotocols): Use pure functions for state machines

---

pallas-crypto/src/hash/hasher.rs
pallas-primitives/src/alonzo/crypto.rs

Native scripts hashes need the tag 0 to compute the correct policy id, see:
https://github.com/input-output-hk/cardano-ledger/blob/736c9295f5896de28fbcedc6a8fc4d509fb78d10/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Scripts.hs#L61-L65
https://github.com/input-output-hk/cardano-ledger/blob/736c9295f5896de28fbcedc6a8fc4d509fb78d10/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Scripts.hs#L163-L171
We can add a comment in the code if you want.

fix(primitives): Fix native scripts policy id (add missing tag)

---

pallas-codec/src/utils.rs
pallas-primitives/src/alonzo/crypto.rs
pallas-primitives/src/alonzo/json.rs
pallas-primitives/src/alonzo/model.rs

After some source code spelunking, this PR adds:
- a mechanism to hash Plutus Data from wire-cbor in an equivalent fashion as the cardano-cli.
- export a Plutus Data struct into JSON format that can be read by the cardano-cli

feat: Implement Plutus Data hashing / JSON

---

Cargo.toml
README.md
examples/block-decode/src/main.rs
pallas-codec/src/utils.rs
pallas-primitives/src/alonzo/model.rs
pallas-primitives/src/byron/address.rs
pallas-primitives/src/byron/crypto.rs
pallas-primitives/src/byron/fees.rs
pallas-primitives/src/byron/model.rs
pallas-primitives/src/byron/time.rs
pallas-primitives/src/framework.rs
pallas-primitives/src/lib.rs
pallas-traverse/Cargo.toml
pallas-traverse/src/block.rs
pallas-traverse/src/iter.rs
pallas-traverse/src/lib.rs
pallas-traverse/src/probe.rs
pallas-traverse/src/tx.rs
pallas/Cargo.toml
pallas/src/ledger.rs

Traversing over block data is a very common task and, at the same time, more complex that it should be. Reasons are:
- Dealing with era-specific details adds a lot of branching in consumer code
- Block data layout makes it harder to iterate over independent transactions
The new `pallas-traverse` lib attempts to abstract away that complexity by creating a multi-era layer on top of the ledger primitives. By providing a `MultiEraBlock` and a `MultiEraTx`, the lib consumer can code against a single structure regardless of the era.
This is an example of how to iterate over Tx of blocks from multiple eras (see `examples/block-decode):
```rust
use pallas::ledger::traverse::MultiEraBlock;
fn main() {
let blocks = vec![
include_str!("blocks/byron.block"),
include_str!("blocks/shelley.block"), …
```

feat: Introduce 'traverse' library

---

pallas-traverse/src/header.rs

Make sure we parse babbage headers based on the era tag of 5 for babbage.

Parse Babbage headers

---

pallas-multiplexer/src/std.rs
pallas-traverse/src/era.rs
pallas-traverse/src/header.rs
pallas-traverse/src/lib.rs

Please review thoroughly and give feedback. I probably didn't do this the most optimal way.

Add Babbage nonce/leader vrf extension

---

examples/n2n-miniprotocols/src/main.rs
pallas-multiplexer/src/agents.rs
pallas-multiplexer/src/lib.rs
pallas-multiplexer/src/mux.rs
pallas-multiplexer/src/std.rs
pallas-multiplexer/tests/integration.rs

The muxer loop uses a lock-free spin to iterate over available ingress channels to select the next payload to be muxed. This is not very efficient since we end up performing a lot of wasted cycles, even when using some backoff mechanism (such as the `snooze` function in the crossbeam crate).
This PR resolves the problem by relying on a single ingress channel, which provides a blocking mechanism using OS-primitives. This removes the need for a loop altogether. After some initial testing, we see that an example chainsync process against a local node maintains the same throughput (~1.5k blocks / sec) while drastically reducing the amount of required CPU (<4%). 
The downside (?) is that now the muxer messages will processed in a FIFO fashion, instead of the randomized approach used in the …

feat(multiplexer): Use single channel for muxer

---

pallas-traverse/src/tx.rs

Seems this field wasn't exposed in the pallas-traverse but we need to access it in Carp
There are some other fields also not exposed (reference_inputs, total_collateral), but I'm keeping this PR small since I need this to unblock myself on Carp 🙏

Expose collateral return in pallas-traverse

---

pallas-traverse/src/tx.rs

Adds the missing `reference_inputs` getter for pallas-traverse

Add reference inputs to pallas-traverse tx

---

pallas-primitives/src/babbage/crypto.rs

This extends the `ToHash` implementation so that it works on DatumOption as well instead of having to type match every time

Add ToHash to DatumOption

---

pallas-traverse/src/witnesses.rs

I'm not sure what is the policy for flattening fields for Pallas. Presumably based on the way blocks and txs are handled, the policy is to flatten stuff when it's shared between eras? Based on this I added some getters for the witness types

Getters for witness fields

---

pallas-addresses/src/lib.rs

While being a nice to have feature in general, this will also allow us to progress filtering by address payment or delegate part in Scrolls in a cleaner way.
Prefixes from [CIP 5](https://cips.cardano.org/cips/cip5/).

feat: add `to_hex` and `to_bech32` methods for address payment and delegation parts

---

pallas-primitives/src/alonzo/model.rs

Useful to sort a vec of TransactionInput in lexical order so that you can point the redeemer to the correct index.

Added PartialOrd and Ord to TransactionInput

---

pallas-codec/src/utils.rs
pallas-traverse/src/lib.rs
pallas-traverse/src/output.rs

* loop through multiasset and concat policy + asset name
* ada unit is lovelace
I can probably create a helper that takes a `&mut assets` to reduce some code. The same double for loop is written 3 times

feat: return all assets at a tx out

---

pallas-codec/src/utils.rs
pallas-primitives/src/alonzo/model.rs

Fixes #211. 
I've seen you already decided to fix the problem of ambiguous CBOR encodings with `KeepRaw` and keeping the initial bytes to be used for hashing etc.
But it is only a plus to make encodings here follow the ones in the [haskell implementation](https://github.com/input-output-hk/plutus/blob/9538fc9829426b2ecb0628d352e2d7af96ec8204/plutus-core/plutus-core/src/PlutusCore/Data.hs#L140), so I made the change.
I've looked on `PlutusData` encoding only. The differences to haskell implementation were:
- empty lists and lists of arguments to a constructor are encoded as a special case as 0-length definite length arrays
- maps are encoded as definite arrays (!)
- bytestrings over 64 bytes are encoded as indefinite bytestrings
I modified those 3 to match haskell. There is a new type …

Match CBOR encoding of plutus data with the haskell implementation.

---

pallas-multiplexer/src/bearers.rs

I have a few structs that contain `Bearer`s that I want to `#[derive(Debug)]` on,, but `Bearer` doesn't implement `Debug`. This adds a `#[derive(Debug)]` for `Bearer`

derive Debug for Bearer

---

pallas-miniprotocols/README.md
pallas-miniprotocols/src/txsubmission/README.md

This was bugging me :sweat_smile: 
Also added a link to the miniprotocol-specific readme from the crate readme; as I write a similar document for each miniprotocol, I intend to add them all here

Fix a few small typos in the txsubmission readme

---

examples/block-download/src/main.rs
examples/n2c-miniprotocols/src/main.rs
examples/n2n-miniprotocols/src/main.rs
pallas-crypto/src/key/ed25519.rs
pallas-miniprotocols/Cargo.toml
pallas-miniprotocols/README.md
pallas-miniprotocols/src/common.rs
pallas-miniprotocols/src/txsubmission/client.rs
pallas-miniprotocols/src/txsubmission/server.rs
pallas-miniprotocols/tests/integration.rs
pallas-multiplexer/README.md
pallas-primitives/src/alonzo/model.rs
pallas-traverse/src/tx.rs

Now consumers of the crate don't have to memorize what channel number means what

Add constants for known miniprotocols

---

examples/block-download/src/main.rs
examples/n2c-miniprotocols/src/main.rs
examples/n2n-miniprotocols/src/main.rs
pallas-miniprotocols/README.md
pallas-miniprotocols/src/common.rs
pallas-multiplexer/README.md
pallas-multiplexer/src/std.rs
pallas-multiplexer/tests/integration.rs

The goal here is to make the use of channels when interfacing with nodes less of a black box; the 0x8000 bit flip is a very surprising behavior if you're not already familiar with it :sweat_smile:

Add client/server use_channel variants

---

pallas-crypto/src/key/ed25519.rs

Both `SecretKey` and `SecretKeyExtended` can be created with any bit pattern, since they both have a constructor which simply fills them with random bytes.
This PR adds `From` impls to allow bidirectional conversion between `SecretKey(Extended)` and the underlying byte arrays

secret key from bytes

---

examples/n2c-miniprotocols/src/main.rs
pallas-miniprotocols/src/txsubmission/client.rs
pallas-miniprotocols/src/txsubmission/codec.rs
pallas-miniprotocols/src/txsubmission/protocol.rs
pallas-miniprotocols/src/txsubmission/server.rs
pallas-miniprotocols/tests/integration.rs

We were still baking in some assumptions about encoding/decoding the TxBody, so this makes it generic in the same way as TxId.
We also provide a default implementation for Cardano specific use cases, since that will be 99% of the cases.

Make TxBody in TxSubmission generic, removing hard-coded encoding/decoding.

---

examples/n2c-miniprotocols/src/main.rs
pallas-network/src/facades.rs
pallas-network/src/miniprotocols/handshake/client.rs
pallas-network/src/miniprotocols/handshake/n2c.rs
pallas-network/src/miniprotocols/handshake/protocol.rs
pallas-network/src/multiplexer.rs

Adding in support for the new handshake option that simply queries the node for its supported protocol versions and then disconnects.

Add Handshake with query for n2c

---

pallas-network/src/miniprotocols/chainsync/client.rs
pallas-network/src/miniprotocols/chainsync/codec.rs
pallas-network/src/miniprotocols/chainsync/mod.rs
pallas-network/src/miniprotocols/chainsync/protocol.rs
pallas-network/src/miniprotocols/chainsync/server.rs
pallas-network/tests/protocols.rs

closes https://github.com/txpipe/pallas/issues/276

feat: chain sync server side

---

Cargo.toml
pallas-codec/Cargo.toml
pallas-codec/README.md
pallas-codec/src/flat/decode/decoder.rs
pallas-codec/src/flat/decode/error.rs
pallas-codec/src/flat/decode/mod.rs
pallas-codec/src/flat/encode/encoder.rs
pallas-codec/src/flat/encode/error.rs
pallas-codec/src/flat/encode/mod.rs
pallas-codec/src/flat/filler.rs
pallas-codec/src/flat/mod.rs
pallas-codec/src/flat/zigzag.rs
pallas-codec/src/lib.rs
pallas-codec/tests/flat.rs
pallas-codec/tests/zigzag.rs

Nothing new is going on within the code itself. I simply popped the crate into pallas_codec as a submodule `pallas_codec::flat`. I also moved over the tests that we had in the crate. In general this is in solid shape and hasn't had any changes for months. That said there could be some things that require love like dealing with BigInt.
relates to #218 
A Rust port of the [Haskell reference implementation](https://github.com/Quid2/flat).
Although it originally seemed interesting to have this as a separate crate on crates.io, I decided that this doesn't make sense because changes to this module are extremely sensitive. Backwards compatibility is an absolute must and so this library needs to be very Cardano specific to always enforce this. So at that point it may as well live somewhere in …

Move flat en/de from aiken to pallas

---

pallas-network/Cargo.toml
pallas-network/src/facades.rs
pallas-network/src/multiplexer.rs

This PR adds a platform specific connect method to the NodeClient so that it can connect to cardano nodes via named pipes on Windows.
Client setup as usual:
```rust
let mut client = 
pallas_network::facades::NodeClient::connect(
r#"\\.\pipe\cardano-node-preprod"#, 
self.configuration.magic
).await
```
Run node with named pipe:
```powershell
cardano-node.exe run ....... --socket-path "\\.\pipe\cardano-node-preprod"
```

feat: Windows Socket Connections

---

pallas-primitives/src/alonzo/model.rs
pallas-primitives/src/babbage/model.rs
pallas-primitives/src/conway/model.rs
pallas-traverse/src/hashes.rs
pallas-traverse/src/output.rs
pallas-traverse/src/witnesses.rs
pallas-txbuilder/src/babbage.rs
pallas-utxorpc/src/lib.rs

also add KeepRaw for nativescript in wits and scriptref

fix: return witness objects for conway era multieratx

---

pallas-network/src/multiplexer.rs

Enable SO_LINGER with a timeout of 0 seconds. This will immediately close the socket by sending a RST packet.
See: https://github.com/IntersectMBO/ouroboros-network/blob/c3d5669bf7c7c3df03c1d80b84adbd77cc7af103/ouroboros-network-framework/src/Ouroboros/Network/Socket.hs#L173-L180

Set so_linger socket option the same as cardano-node

---

examples/n2c-miniprotocols/src/main.rs
pallas-network/src/facades.rs
pallas-network/src/multiplexer.rs

This PR implements the entry point code to support connection to `cardano-node` via `NamedPipes` for windows. 
`examples/n2c-miniprotocols` code has been updated to showcase `NamedPipes` connection functionality.
credits to @olofblomqvist for suggesting `tokio::io::split` to split the NamedPipe instance into ReadHalf and WriteHalf instances.

Implement NamedPipes entry point

---

pallas-codec/Cargo.toml
pallas-codec/src/flat/decode/decoder.rs
pallas-codec/src/flat/decode/mod.rs
pallas-codec/src/flat/encode/encoder.rs
pallas-codec/src/flat/encode/mod.rs
pallas-codec/src/flat/zigzag.rs
pallas-codec/tests/flat.rs
pallas-codec/tests/zigzag.rs

This commits fixes the flat encoding and decoding (and consequently, the zigzag) for large integers in the following ways:
- It removes support for encoding and decoding i128 values.
- It optionally (feature = "num-bigint") introduces encoding and decoding of large sized integers through the num-bigint::BigInt type.
Without the feature enabled, it is still possible to encode and decode isize values; but the use of i128 is now prohibited (as it would overflow on boundaries) in favor of arbitrarily sized integers.
The commit also introduces a property roundtrip for encoding and decoding large integers, which was missing and thus, failed to identify the overflow problem.
See related issue: https://github.com/aiken-lang/aiken/issues/796

fix(codec) Fix flat encoding and decoding of arbitrarily size integers

---

examples/n2c-miniprotocols/src/main.rs
pallas-codec/src/utils.rs
pallas-network/src/miniprotocols/localstate/queries_v16/codec.rs
pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs
pallas-network/tests/protocols.rs

In case we search for specific pools: currently we have [one](https://github.com/IntersectMBO/ouroboros-consensus/blob/63fa2385a360eff10208c09f8ec055a13dae1984/ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Query.hs#L550) pool per request limit. [Empty](https://github.com/IntersectMBO/ouroboros-consensus/blob/63fa2385a360eff10208c09f8ec055a13dae1984/ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Query.hs#L554) pools means all pools.
the `cardano-cli` has the same behavior due to this limitation.
fixes #395

feat: implement stake snapshot local state query

---

examples/n2c-miniprotocols/src/main.rs
pallas-network/src/miniprotocols/localstate/queries_v16/codec.rs
pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs
pallas-network/tests/protocols.rs

In the upstream implementation we are limited by 1 pool per request.
fixes #397

fix: support multiple pools search in stake snapshot local state query

---

pallas-utxorpc/src/lib.rs

This PR adds new fields to UTxORPC Data:
`Tx->Hash`
`Block->Height`
This would be dependent if the rust sdk for UTxORPC is merged and published: https://github.com/utxorpc/spec/pull/34

chore(utxo-rpc): Expose Tx->Hash & Block->Height

---

examples/n2n-miniprotocols/src/main.rs
pallas-network/src/facades.rs
pallas-network/src/miniprotocols/keepalive/client.rs
pallas-network/src/miniprotocols/keepalive/protocol.rs
pallas-network/src/miniprotocols/keepalive/server.rs

In this PR we introduce a background keep-alive loop as part of the PeerClient facade. This avoids the need for upper layers to implement their own logic, which is pretty standard.
On following PRs we'll introduce a way to configure the keep-alive interval and a way to skip it altogether.

feat(network): implement background keep-alive loop

---

examples/n2c-miniprotocols/src/main.rs
pallas-network/src/miniprotocols/chainsync/client.rs

When actually consuming the chainsync client, initially the consumer
should call request_next repeatedly. However, once you are caught up,
you will get an "Await" response, which says we've requested the next
block, but the server doesn't have one for us, and will let us know when
one is available. If we request_next again, it fails.
In fact, even the example was misleading in this way!
The correct way to consume it was to check if you have agency, and if
so, either await or recieve.
If you tried to do this, though, especially when mixing it with other
future things (like select! on a cancellation token), then things could
get messy, because even though they return the same type, the impl
Future instances were opaque to the compiler.
This convenience method makes it nice and simple to …

Add an extra ergonomic method for n2c chainsync

---

Cargo.toml
examples/crawler/.gitignore
examples/crawler/Cargo.toml
examples/crawler/README.md
examples/crawler/src/main.rs

While working on Amaru, we'll likely want to grab lots of example data. This adds a small utility to easily grab one block, one tx, or blocks/txs matching some predicate.
Example usage:
- implement `tx_matches` or `block_matches` at the top of the file
- run on a machine with a local cardano node
- For command line arguments, see:
```
cargo run --bin crawler -- --help
```

Add a simple Crawler example

---

pallas-hardano/src/storage/immutable/mod.rs

We have found that according to this docs https://mithril.network/doc/glossary/#immutable-file-number.
Last chunk files of the immutable db is not really immutable.
And as a consequence last chunk files also could have an invalid and corrupted data, which we have faced with some mithrill snapshots (Basically that case also described here https://github.com/txpipe/pallas/pull/426).
This solution suggests just to exclude the last chunk files during the read, to preserve an expected state from the immutable storage, that's it's finalised state.

fix: Exclude last chunk files during immutable db read

---

pallas-utxorpc/Cargo.toml
pallas-utxorpc/src/lib.rs

Enable the provision of a context for mapping tx inputs to their respective tx output.
Previous PR ([449](https://github.com/txpipe/pallas/pull/449)) attempted to use an outdated branch as a base. This one forks from main and implements the necessary additions from scratch.

Added block context for mapping tx inputs as outputs

---

pallas-applying/src/alonzo.rs
pallas-applying/src/babbage.rs
pallas-applying/src/byron.rs
pallas-applying/src/shelley_ma.rs
pallas-applying/src/utils.rs

Fix the computation of the size of a transaction by additionally adding the witness set CBOR length and the auxiliary data CBOR length

Fix tx size in pallas-applying

---

examples/n2n-miniprotocols/src/main.rs
pallas-network/src/facades.rs
pallas-traverse/src/block.rs
pallas-traverse/src/header.rs
pallas-traverse/src/lib.rs

Updates:
Ensure we can parse block header values of 5..6 as BabbageCompatible for both Babbage and Conway eras. The previous code had a Conway header falling back and attempting to parse as AlonzoCompatible.
Refactoring:
I changed AlonzoCompatible -> ShelleyCompatible for the block headers. BlockHeaders represent forward compatibility. In other words, we only get a new category for headers named after the first Era in which it changed.
Babbage -> BabbageCompatible since it now also includes conway BlockHeaders.
So, shelley, allegra, mary, alonzo blocks contain block headers that are shelley compatible.
babbage and conway blocks contain block headers that are babbage compatible.

feat(traverse): Decode Conway block headers properly

---

pallas-network/src/miniprotocols/txmonitor/codec.rs

Rationale:
the node answers with [129, 6] if it sent all tx's from the snapshot
More information:
https://ogmios.dev/mini-protocols/local-tx-monitor/#how-to-use
```
1. acquireMempool  → acquireMempoolResponse
2. nextTransaction → nextTransactionResponse t0
3. nextTransaction → nextTransactionResponse t1
4. nextTransaction → nextTransactionResponse t2
5. nextTransaction → nextTransactionResponse null
```

network: Fix return of empty value in the ResponseNextTx

---

Cargo.toml
README.md
pallas-math/Cargo.toml
pallas-math/README.md
pallas-math/src/lib.rs
pallas-math/src/math.rs

Placeholder create for the future pallas-math functionality.

Initial README for pallas-math

---

.github/workflows/validate.yml
pallas-math/Cargo.toml
pallas-math/src/lib.rs
pallas-math/src/math.rs
pallas-math/src/math_gmp.rs
pallas-math/src/math_num.rs
pallas-network/tests/protocols.rs

Enables checks to run under Windows.
Performs the golden tests for the `exp()` function. Addtl math will be added in a later PR. 
The `gmp` feature defines the `Decimal` struct that uses the underlying `gmp` math library.
The `num` feature defines the `Decimal` struct that uses the underlying num-bigint math library.
`gmp` is set as the default and `num` must be enabled when running under Windows. The primary trait for `Decimal` is called `FixedPrecision`. In the future, we could have additional math libraries implement this if they are better/faster, etc...
I'm unsure about making `gmp` a default feature. I'm wondering if it makes more sense to instead create a `pallas-math-gmp` and `pallas-math-num` crate that depend on `pallas-math`. Suggestions are welcome for the best way to …

feat: Add support for some math functions

---

pallas-primitives/src/alonzo/model.rs
pallas-primitives/src/conway/model.rs

- :round_pushpin: **Provide slightly better error when failing to decode Plutus data.**
- :round_pushpin: **Expose GovActionId, Constitution & Anchor inner fields**
There's otherwise no way to do anything with those objects, except serializing them.

Expose (necessary) hidden struct fields

---

pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs
pallas-primitives/src/conway/model.rs

- :round_pushpin: **Expose private struct fields for ExUnitPrices.**
- :round_pushpin: **Fix UpdateDRepCert variant argument.**
They are isomorphic, but for the sake of correctness, it's better that way.

0.30.0+patch

---

pallas-codec/src/utils.rs
pallas-crypto/src/vrf/mod.rs
pallas-primitives/src/babbage/model.rs
pallas-traverse/src/header.rs

Adding some ergonomic improvements to make Amaru code less ugly.

feat(crypto): Add extra types and conversions

---

pallas-addresses/Cargo.toml
pallas-crypto/Cargo.toml
pallas-crypto/README.md
pallas-crypto/src/kes/mod.rs
pallas-crypto/src/lib.rs
pallas-primitives/src/alonzo/model.rs
pallas-primitives/src/babbage/model.rs
pallas-primitives/src/conway/model.rs
pallas-traverse/src/hashes.rs
pallas-traverse/src/header.rs
pallas-traverse/src/lib.rs

This code modifies block headers so that the HeaderBody bytes are wrapped in KeepRaw. These raw bytes are used in the validation of KES signatures.
pallas-crypto has been updated with wrappers around kes signatures for both evolving the secret key as well as verifying signatures with the public key.

feat(crypto): Add Key Evolving Signatures (KES)

---

pallas-applying/src/alonzo.rs
pallas-applying/tests/alonzo.rs
pallas-applying/tests/babbage.rs
pallas-primitives/src/conway/model.rs
pallas-primitives/src/plutus_data.rs
pallas-traverse/src/hashes.rs
pallas-traverse/src/redeemers.rs
pallas-traverse/src/witnesses.rs
pallas-txbuilder/src/transaction/serialise.rs

Computing "script data hash" requires redemeers, witness-set datums and language views.
To make the hash consistent across encoding roundtrips, this PR replaces some internal structs in the primitives with CBOR-aware structs (eg: MaybeIndexArray).
A following PR will introduce the hash compute logic.

refactor: support roundtrip encoding for script data hash components

---

pallas-txbuilder/src/conway.rs

Babbage allowed for empty redeemer arrays in the witness set, but Conway does not. If there are no redeemers, field `5` should not be included. This PR changes the logic to only include redeemers when the set of redeemers is non-empty.

Fix invalid serialization of Conway transactions when there are no redeemers

---

pallas-math/Cargo.toml
pallas-math/src/math.rs
pallas-math/src/math_malachite.rs

LazyLock is now the preferred way of doing lazy static initialization.

fix(math): update once_cell::Lazy -> std::sync::LazyLock

---

CHANGELOG.md
pallas-txbuilder/src/conway.rs
pallas-txbuilder/src/transaction/model.rs

Adding a signature to a conway era transaction causes a `called `Result::unwrap()` on an `Err` value: CorruptedTxBytes` error.
```rust
let signed_tx_cbor = tx
// called `Result::unwrap()` on an `Err` value: CorruptedTxBytes
.add_signature(witness_public_key, witness_vector)
.unwrap()
.tx_bytes;
```
This error comes from line 685 in model.rs of the txbuilder.
If you change the `babbage` call into a `conway` call then it does not throw the error. 
This PR changes the `babbage` to `conway` on all the things. Also, it adjusts the witness building as pushing to a set is not possible and requires coverting back to a vector then back to an empty set.
This PR passes all current tests. There is no open issue on this topic as it brought up in discord.

making changes to tx builder model

---

examples/n2c-miniprotocols/src/main.rs
pallas-network/src/miniprotocols/localstate/queries_v16/codec.rs
pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs
pallas-network/tests/protocols.rs

This PR adds the `get_utxo_by_txin` query and adds an integration test at `examples/n2c-miniprotocols`.
It also solves #546 by using the `try_join` macro that prioritizes error exposure.

feat(network): implement GetUTxOByTxIn, fixed tests

---

examples/n2c-miniprotocols/src/main.rs
pallas-network/src/miniprotocols/localstate/client.rs
pallas-network/src/miniprotocols/localstate/queries_v16/codec.rs
pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs
pallas-network/tests/protocols.rs

This PR implements the named query, along with its corresponding unit-test at `protocols.rs` and integration one at `examples/n2c-miniprotocols`.
I took the opportunity to streamline the imports at the test file, and to provide more informative panics. This comprises modifications through many LoC, but the main ones lie in two blocks starting at lines 790 and 1127, resp, of `protocols.rs`. We think that it should be reasonable to re-engineer this file, but further modifications will be part of another PR.

feat(network): implement `GetFilteredDelegationsAndRewardAccounts`

---

examples/n2c-miniprotocols/src/main.rs
pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs
pallas-network/tests/protocols.rs

A field of the `Pool` struct (corresponding to the node's `PoolDistr`) was a naively encoded rational number `Fraction`; this one is indeed needed in the genesis config struct, which I renamed from `Genesis` to the more explicit `GenesisConfig`. 
In the case of `ProtocolParam`, the `ProtocolVersion` is now a tuple `(major, minor)`.
Both corrections have an impact on the `examples/n2c-miniprotocols` folder; two broken examples there now run smoothly. In that folder, I moved the initial `Point` of the block-fetching performed by `do_chainsync` to a more recent moment in order to be able to witness the reaching of the chain tip.
This solves #496.

fix(network): correct PoolDistr and update ProtocolParam

---

pallas-math/Cargo.toml
pallas-math/src/lib.rs
pallas-math/src/math.rs
pallas-math/src/math_dashu.rs

Malachite has a bad license for our open-source project. 
https://github.com/mhogrefe/malachite/issues/52#issuecomment-2406980210
This replaces our bigint implementation with dashu that has a nicer license. It's not quite as fast, but it will work for now. The fastest would be gmp or Rug based on gmp, but that relies on native code that doesn't compile on windows.
We need to ensure we maintain windows compatibility for the Amaru project and the possibility of full-node wallets.

feat(math): Replace math library - malachite -> dashu

---

pallas-network/src/miniprotocols/chainsync/codec.rs

IntersectNotFound carries both a label/tag and the tip of the node; so the size of the array must be of length 2. 
See also: https://github.com/IntersectMBO/ouroboros-network/blob/efb64c78b8eb56027d9af12e3e786c5261ad5bd3/ouroboros-network-protocols/src/Ouroboros/Network/Protocol/ChainSync/Codec.hs#L144

Fix IntersectNotFound CBOR encoding

---

pallas-applying/Cargo.toml
pallas-applying/src/babbage.rs
pallas-applying/src/conway.rs
pallas-applying/src/lib.rs
pallas-applying/src/utils.rs
pallas-applying/src/utils/validation.rs
pallas-applying/tests/babbage.rs
pallas-codec/src/utils.rs

This implementation adds support for Conway Phase One validation. It currently checks the same rules that the Babbage implementation uses.
Additionally, since Conway and Babbage share the same checks and throw the same errors, the validation error BabbageError has been renamed to PostAlonzoError to accommodate both eras. I also added the thiserror crate to pallas-applying for better error handling

feat: conway phase one validation implementation

---

pallas-configs/src/shelley.rs
test_data/golden-shelley-genesis.json

This fixes the Shelley part of #296
Notably,
- fix the type for `pools`
- fix the type for `initial_funds`
Additionally, this PR adds a new `shelley_utxos` helper function to help unblock this Dolos issue: https://github.com/txpipe/dolos/issues/427
This PR introduces a new "golden" test, which is taken from the Haskell codebase [here](https://github.com/IntersectMBO/cardano-ledger/blob/ff526dfe6460ae5a6ba398b091d6da52b539b285/eras/shelley/test-suite/test/Golden/ShelleyGenesis)
Notably, you can find the original code for this serialization logic in the Haskell codebase at the following:
- pool parsing [here](https://github.com/IntersectMBO/cardano-ledger/blob/ff526dfe6460ae5a6ba398b091d6da52b539b285/libs/cardano-ledger-core/src/Cardano/Ledger/PoolParams.hs#L231-L243)
- initial funds UTXO …

Fix Shelley genesis parsing

---

pallas-network/src/miniprotocols/mod.rs
pallas-network/src/miniprotocols/peersharing/client.rs
pallas-network/src/miniprotocols/peersharing/codec.rs
pallas-network/src/miniprotocols/peersharing/mod.rs
pallas-network/src/miniprotocols/peersharing/protocol.rs
pallas-network/src/miniprotocols/peersharing/server.rs

This PR adds the implementation of the `peersharing` protocol.

feat(network): add `peersharing` protocol module

---

pallas-utxorpc/src/lib.rs

Before a certain point in time, datums were provided in a txs witness set and not directly attached to the outputs.
As a utxorpc client, it is very difficult to figure out which datums correspond to which outputs since it would require hashing the datums in the witness set which are not in their raw form.
This PR performs the mapping of witness set datums to their corresponding outputs in the utxorpc module alleviating this hardship.
Note: This implementation works but I expect there might be a better way to things. One additional improvement would be adding the original cbor in addition to the payload but I wasn't sure how best to do this.

Map witness datums to tx outputs and inputs in utxorpc module

---

pallas-network/src/miniprotocols/peersharing/codec.rs
pallas-network/src/miniprotocols/peersharing/protocol.rs
pallas-network/tests/protocols.rs

- The peer client start the peersharing mini-protocol by sending `MsgShareRequest` to the peer server.
- The peer client receives a message via `MsgSharePeers` that contains PeerAddresses from the peer server.
- PeerAddress enum contains Ipv4 and Ipv6
- The CDDL specification for peer addresses requires:
- IPv4: An array [0, word32, portNumber]
- IPv6: An array [1, word32, word32, word32, word32, flowInfo, scopeId, portNumber]
- The original implementation decodes the IPv4 address as raw bytes instead of u32.
- The original implementation did not include the extra fields flowInfo and scopeId for IPv6.
- The original implementation did not segment and encode IPv6 into four 32-bit words as per the CDDL.
- **IPv4 Issue**: The address was being decoded as raw bytes rather than as a single …

fix(network): encoding and decoding of peersharing peer address

---

pallas-network/src/facades.rs
pallas-network/src/miniprotocols/handshake/n2n.rs

- The handshake mini-protocol only replies with `MsgAcceptVersion` and `MsgRefuse` currently.
- Upon testing, the negotiated version doesn't inherit the actual PeerSharing config of the server
- So there was no actual way for us to know if the peer server has peersharing capabilities
- We needed a way for us to know the peer server's supported version table and version data
- We can only do that if the server replies with `QueryReply`
- ***However, if we merely add an option for us to do queries to the current setup, the connection closes as soon as a Query Reply is expected.***
- ***Thus, we need a separate function for it that connects only to perform a `query handshake`.***
- This specific feature is particularly useful for the peersharing mini-protocol implementation in Boros.
- …

feat(network): peer client version table query support

---

pallas-network/src/miniprotocols/localtxsubmission/codec.rs

Currently, the rejection reason is always prefixed with `8202`, because the entire `d.input()` is copied there. And `d.input()` always contains the whole input.
An (incorrect) example of a `FeeTooSmallUTxO` error:
```cbor
82                                      # array(2)
02                                   # unsigned(2)
81                                   # array(1)
82                                # array(2)
06                             # unsigned(6)
82                             # array(2)
82                          # array(2)
01                       # unsigned(1)
82                       # array(2)
00                    # unsigned(0)
83                    # array(3)
06                 # unsigned(6)
1B 000000025050D4DD # unsigned(9937409245)
1A 003D0E39        # …
```

fix(network): drop the `[2,…]` message tag wrapper from the rejection reason

---

pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs

Just parses another field on the pparams map. Tested this locally and it works.

Add plutus v3 cost model to local PParams

---

pallas-applying/src/utils.rs
pallas-codec/src/utils.rs
pallas-traverse/src/header.rs

Make `KeepRaw` store the original data as a `Cow<'b, [u8]>` instead of a `&'b [u8]`, and add a `to_owned` method. Justification for this change is in #599, but tl;dr it lets you avoid awkward lifetime problems.
This is a breaking change, the `raw_cbor()` method now returns a `&[u8]` instead of a `&'b [u8]`. In practice, this means that a reference to the raw bytes can no longer outlive a reference to the structure itself. 
Also adds an `as_ref` method to the `Nullable<T>` helper, to fix a lifetime problem this changed introduced.

feat(codec): allow KeepRaw to own its data

---

examples/n2c-miniprotocols/src/main.rs
pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs
pallas-network/tests/protocols.rs

Fix some localstate queries which are treating `PParamsUpdate` and `ProtocolParam` as the same type. The former describes (potential) updates to protocol parameters, the latter describes the current or previous set of protocol parameters.
With this change, the n2c localstate queries in the examples directory all succeed. Without it they were hitting decoding errors.

Separate PParamsUpdate from ProtocolParam

---

.github/workflows/validate.yml
.gitmodules
pallas-codec/src/utils.rs
pallas-network/Cargo.toml
pallas-network/src/miniprotocols/handshake/protocol.rs
pallas-network/src/miniprotocols/localstate/codec.rs
pallas-network/src/miniprotocols/localstate/queries_v16/codec.rs
pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs
pallas-network/tests/protocols.rs

Stacked with #587, review that first.
Explores how we can test the [LocalStateQuery API](https://github.com/cardano-scaling/cardano-blueprint/issues/25) that is being created in course of the blueprint initiative.
~~Note that the first (and only) API query example for `getSystemStart` is actually failing to decode the result, because the `year` is actually a big negative number = the rust implementation behaves different than the CDDL specification (I personally think unsigned numbers would be in fact nicer though .. or maybe even use `time` for this particular query result).~~
This PR now also fixes the `SystemStart` data type (incl. derived encoder + decoder)

Cardano blueprint localstatequery tests

---

.gitmodules

I tried updating my project to depend on the latest and greatest pallas commit, and [the build started failing](https://github.com/hyperledger/firefly-cardano/actions/runs/14669906929/job/41174115507?pr=36) because of a permission error:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
IME, the easiest way to get around these kinds of errors is to use https urls for submodules. So, switch the project to do that.
I can confirm that this fixes my project's build.

Use HTTPS url for cardano-blueprint submodule

---

pallas-network/src/facades.rs
pallas-network/src/miniprotocols/README.md
pallas-network/src/miniprotocols/common.rs
pallas-network/src/miniprotocols/localmsgnotification/README.md
pallas-network/src/miniprotocols/localmsgnotification/client.rs
pallas-network/src/miniprotocols/localmsgnotification/codec.rs
pallas-network/src/miniprotocols/localmsgnotification/mod.rs
pallas-network/src/miniprotocols/localmsgnotification/protocol.rs
pallas-network/src/miniprotocols/localmsgnotification/server.rs
pallas-network/src/miniprotocols/localmsgsubmission/README.md
pallas-network/src/miniprotocols/localmsgsubmission/client.rs
pallas-network/src/miniprotocols/localmsgsubmission/codec.rs
pallas-network/src/miniprotocols/localmsgsubmission/mod.rs
pallas-network/src/miniprotocols/localmsgsubmission/protocol.rs
pallas-network/src/miniprotocols/localmsgsubmission/server.rs
pallas-network/src/miniprotocols/localtxsubmission/mod.rs
pallas-network/src/miniprotocols/localtxsubmission/protocol.rs
pallas-network/src/miniprotocols/localtxsubmission/server.rs
pallas-network/src/miniprotocols/mod.rs
pallas-network/tests/protocols.rs

This PR includes the implementation of the **n2c DMQ ([Decentralized Message Queue - CIP-0137](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0137)) in `pallas-network`**:
- Added **n2c local message submission** mini-protocol:
- Based on the implementation of the existing `GenericClient` of n2c local tx submission
- Based on the implementation of the new `GenericServer` of n2c local tx submission
- Added **n2c local message notification** mini-protocol
- Updated **n2c local tx submission** mini-protocol with a `GenericServer` implementation

feat: n2c local message submission and notification mini protocols

---

pallas-primitives/Cargo.toml
pallas-primitives/src/plutus_data.rs

> [!NOTE]
>
> It would be really nice if this could also be backported on top of v0.32.0 and released as we (Amaru & Aiken) aren't ready to upgrade to v1.0.0 and those are critical fixes. We can always keep a fork but that prevents publishing to crates.io which is quite annoying.
- :round_pushpin: **fix: ensure PlutusData encoding can roundtrip.**
- :round_pushpin: **fix: PlutusData ordering and equality**
This has been broken for a while, and would ultimately result in all kind of errors and unexpected behaviours and errors. An example is when comparing two data in the Plutus Virtual Machine, they must match regardless of the chosen encoding (if one used an indefinite array and the other used a definite array, that shouldn't matter).
It gets really subtle, for example with 'BigInt', as …

PlutusData fixes and tests

---

pallas-primitives/src/alonzo/model.rs

There were 2 problems here:
1. The encoder would produce invalid CBOR in for the N-of-K variant of NativeScript which is encoded as an array of 3 elements, but marked as containing 2.
2. The decoder doesn't consume all the bytes it should; thus succeeding to decode partial / incomplete (and thus invalid) CBOR sequences. Note that while fixed in this particular instance for NativeScript, the problem is recurring across pretty much all list-like decoders within Pallas and should probably be subject to a larger overhaul.

fix: encoding and decoding of NativeScript

---

pallas-network/src/miniprotocols/localmsgnotification/client.rs
pallas-network/src/miniprotocols/localmsgnotification/codec.rs
pallas-network/src/miniprotocols/localmsgnotification/protocol.rs
pallas-network/src/miniprotocols/localmsgnotification/server.rs
pallas-network/src/miniprotocols/localmsgsubmission/codec.rs
pallas-network/src/miniprotocols/localmsgsubmission/protocol.rs
pallas-network/tests/protocols.rs

This PR includes updates of the [**CIP-0137**](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0137/README.md):
- **The structure of the DMQ messages has evolved**:
- removed the `blockNumber` field
- removed the `ttl` 
- added an `expiresAt` field (`word32`)
- added a `coldVerificationKey` field (`word32`)
- split the message payload from the KES signature and verification material
- **The `MsgServerDone` message has been removed from the `n2c local message notification` mini-protocol**
These modifications are being reflected into a [CIP update](https://github.com/cardano-scaling/CIPs/pull/15).

refactor(network): update DMQ message
