txpipe/pallas

pallas-multiplexer/src/bearers.rs
Disable Unix socket on non-unix platforms
=> feat: Disable Unix socket on non-unix platforms

pallas-multiplexer/tests/integration.rs
=> ci(multiplexer): Fix connection refused error in integration tests

pallas-chainsync/src/clients.rs
=> fix(chainsync): Stop machine when intersect is not found

pallas-machines/src/payloads.rs, pallas-multiplexer/src/lib.rs
=> fix(machines): Don't warn on expected end-of-input errors

pallas-alonzo/src/model.rs
fix https://github.com/txpipe/oura/issues/113
based on https://github.com/txpipe/oura/issues/113#issuecomment-1025171447
=> fix(alonzo): ExUnits steps overflow

pallas-crypto/Cargo.toml, pallas-crypto/src/hash/hash.rs, pallas-miniprotocols/Cargo.toml, pallas-miniprotocols/src/payloads.rs, pallas-primitives/Cargo.toml, pallas-primitives/src/alonzo/model.rs, pallas-primitives/src/byron/model.rs, pallas-primitives/src/utils.rs
includes and fixes
- https://github.com/txpipe/pallas/pull/54
- https://github.com/txpipe/pallas/pull/55
=> build(deps): minicbor-0.14, minicbor-derive-0.9.0, fix build

pallas-codec/src/utils.rs, pallas-primitives/src/alonzo/model.rs
=> fix: Use correct struct for metadatum labels

pallas-multiplexer/src/bearers.rs
Allow the user to specify a connect timeout. Useful for the cncli ping command so we don't wait a very long time just to tell the user it didn't work.
=> Allow a specified timeout on tcp connection

pallas-traverse/src/assets.rs, pallas-traverse/src/lib.rs, pallas-traverse/src/output.rs
Took the liberty of adjusting the asset access API a little bit. Added some extra helper methods and some docstrings.
=> feat(traverse): Add helper methods to Asset data

Cargo.toml, pallas-upstream/Cargo.toml, pallas-upstream/README.md, pallas-upstream/src/api.rs, pallas-upstream/src/blockfetch.rs, pallas-upstream/src/chainsync.rs, pallas-upstream/src/cursor.rs, pallas-upstream/src/framework.rs, pallas-upstream/src/lib.rs, pallas-upstream/src/plexer.rs, pallas-upstream/src/wellknown.rs, pallas/Cargo.toml, pallas/src/network.rs
This new crate provides an opinionated but simple way retrieving block data from an upstream node. This current implementation provides n2n logic for performing chain-sync and block-fetch operations.
=> feat: Introduce Upstream crate

pallas-traverse/src/aux.rs, pallas-traverse/src/lib.rs, pallas-traverse/src/tx.rs
Provide getters for aux data scripts (native and plutus)
=> feat(traverse): Expose aux data scripts

pallas-network/src/miniprotocols/README.md
=> chore: Update mini-protocol pdf README link

examples/n2c-miniprotocols/src/main.rs, pallas-codec/src/utils.rs, pallas-network/Cargo.toml, pallas-network/src/miniprotocols/localstate/codec.rs, pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs, pallas-network/tests/protocols.rs
fixes https://github.com/txpipe/pallas/issues/316
=> add stake distribution local state query

pallas-network/src/miniprotocols/common.rs, pallas-network/src/miniprotocols/handshake/n2c.rs
=> feat(network): add sanchonet compatibility

examples/n2n-miniprotocols/Cargo.toml, examples/n2n-miniprotocols/src/main.rs, pallas-network/Cargo.toml, pallas-network/src/multiplexer.rs
also improves the n2n-miniprotocols example code.
=> fix(network): Add tcp_nodelay

pallas-applying/src/shelley_ma.rs
I think I might have missed this when I made native scripts KeepRaw, feel free to change this if there is a better way to make it work
=> fix: update pallas-applying to work with keepraw native scripts

examples/n2c-miniprotocols/src/main.rs, pallas-network/src/miniprotocols/localstate/queries_v16/codec.rs, pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs, pallas-network/tests/protocols.rs
=> add `get_current_pparams` local state query

pallas-traverse/src/tx.rs
Closes #391 
Adding:
- Total_collateral
- Collateral
- Reference_inputs
=> Adding missing Conway transaccion field

pallas-rolldb/src/wal/store.rs, pallas-rolldb/src/wal/stream.rs, pallas-rolldb/src/wal/tests.rs
https://github.com/txpipe/dolos/issues/173
=> feat: optionally overlap WAL with immutable part of chain when pruning

pallas-traverse/Cargo.toml, pallas-traverse/src/tx.rs, pallas-traverse/src/witnesses.rs, pallas-utxorpc/Cargo.toml, pallas-utxorpc/src/lib.rs, test_data/u5c1.json
=> map some redeemers

pallas-codec/src/utils.rs, pallas-primitives/src/babbage/model.rs, pallas-primitives/src/conway/model.rs, pallas-traverse/src/assets.rs, pallas-traverse/src/lib.rs, pallas-traverse/src/output.rs, pallas-traverse/src/tx.rs, pallas-traverse/src/withdrawals.rs
This properly supersedes #357.
=> Use Conway types in places they are meant to.

pallas-traverse/src/value.rs
Add `into_conway` to `MultiEraValue`. It's the same thing as `into_alonzo`, except into Conway.
=> feat(traverse): implement MultiEraValue.into_conway

examples/n2c-miniprotocols/src/main.rs, pallas-txbuilder/src/transaction/mod.rs, pallas-txbuilder/src/transaction/model.rs
Each field of a StagingTransaction and BuiltTransaction should derive Clone. I tested this on-chain, and it is working as expected. All tests are passing.
=> added derive clone to the required structs for StagingTransaction

examples/n2c-miniprotocols/src/main.rs, pallas-network/Cargo.toml, pallas-network/src/miniprotocols/localstate/queries_v16/codec.rs, pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs, pallas-network/src/miniprotocols/localstate/queries_v16/primitives.rs, pallas-network/tests/protocols.rs
This PR implements the named local state query, along with its corresponding unit-test at `protocols.rs` and the integration one at `/examples/n2c-miniprotocols`.
Depends on #552, which should be merged first.
=> feat(network): Get stake pool parameters

pallas-network/src/miniprotocols/localstate/queries_v16/codec.rs, pallas-network/src/miniprotocols/localstate/queries_v16/mod.rs, pallas-network/tests/protocols.rs
This PR implements the named query, along with its corresponding unit-test at protocols.rs.
=> Utxo whole

pallas-network/src/facades.rs, pallas-network/src/miniprotocols/common.rs, pallas-network/tests/protocols.rs
This PR adds the Peer Sharing protocol to the N2N Ouroboros client and server, together with a unit test of the protocol.
=> feat(network): include Peer Sharing protocol with unit test

pallas-network/src/miniprotocols/localtxsubmission/codec.rs, pallas-network/src/miniprotocols/localtxsubmission/protocol.rs
This PR completes the variants of the following tx submission errors:
- `TxError`, corresponding to [ConwayLedgerPredFailure](https://github.com/IntersectMBO/cardano-ledger/blob/d30a7ae828e802e98277c82e278e570955afc273/eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ledger.hs#L138),
- [(Conway)UtxowFailure](https://github.com/IntersectMBO/cardano-ledger/blob/d30a7ae828e802e98277c82e278e570955afc273/eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Utxow.hs#L94), and
- [(Conway)UtxoFailure](https://github.com/IntersectMBO/cardano-ledger/blob/d30a7ae828e802e98277c82e278e570955afc273/eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Utxo.hs#L78C6-L78C28),
by using `AnyCbor` when necessary. `TxError` has an `u8` variant for conformance to preexisting (Babbage) tests.
The codecs have been …
=> feat(network): Toplevel LocalTxSubmission variants + revised codec

pallas-primitives/src/conway/model.rs
... here replaced by the corresponding derives. Non-exhaustive, more to come in next PR.
=> refactor: Remove unnecessary codecs

pallas-primitives/src/alonzo/json.rs, pallas-primitives/src/alonzo/model.rs, pallas-traverse/src/hashes.rs, pallas-traverse/src/header.rs, pallas-traverse/src/lib.rs, pallas-validate/src/phase_one/alonzo.rs, pallas-validate/src/phase_one/shelley_ma.rs, pallas-validate/src/utils.rs
=> refactor(primitives): Remove Alonzo Pseudo and Minted structs

pallas-traverse/src/governance.rs, pallas-traverse/src/tx.rs, pallas-txbuilder/src/conway.rs, pallas-txbuilder/src/scriptdata.rs, pallas-utxorpc/src/certs.rs, pallas-utxorpc/src/lib.rs, pallas-validate/src/phase1/alonzo.rs, pallas-validate/src/phase1/babbage.rs, pallas-validate/src/phase1/conway.rs, pallas-validate/src/phase1/shelley_ma.rs, pallas-validate/src/utils.rs
Addressing `cargo clippy -- -D warnings` issues.
=> chore: clippy lints

pallas-txbuilder/src/transaction/model.rs
Instead of passing in PrivateKey from pallas_wallet, let's implement a trait for signing and getting the public key for the SecretKey and SecretKeyExtended types.
=> adding a ed235519 trait for signing and publickey

pallas-traverse/src/tx.rs
Conway is out and attempt to decode Conway comes first
=> chore: remove outdated comment.

pallas-validate/src/phase2/tx.rs
=> feat: added logs to phase2 TxEvalResult
